### ISSUE TITLE
Pointclouds reduce the gazebo Real Time Factor

### ISSUE THREAD

**Issue by Morgantiz** [ADVRHumanoids/concert_description#5]
I noticed that if you subscribe to the pointclouds the Real Time Factor drops down. 
To replicate the problem just make a rostopic echo on the pointcloud topics (probably gazebo does not compute and publish the pointclouds if no one is subscribed).  
I think that change the plugin used inside the urdf from ray to gpu_ray could solve the problem. (https://answers.ros.org/question/352715/gazebo-real-time-factor-going-down/)

**Comment by EdoardoRomiti** [comment]
Hi @Morgantiz , I just tried and it does indeed help with Gazebo RTF.
Also code modification is really minimal so we can easily switch to gpu_ray.
Only thing, we don't have much experience using it, do you guys at Fraunhofer have more? Have you been using it already?
I just saw there are some open issues about some limitations of gpu_ray (see for instance: https://bitbucket.org/DataspeedInc/velodyne_simulator/issues/15/gpu-mode-very-roughly-resoluted-scans-in), but if you already have experience with it we can go for it. 
FYI @alaurenzi

**Comment by fmros** [comment]
Hy @EdoardoRomiti thanks for trying this out!

Until now we can't tell from experience, I propose we put this feature onto a separate branch and try to collect feedback from users.

What do you think?

**Comment by EdoardoRomiti** [comment]
@Morgantiz @fmros Since the code modifications is minimal i've decided to add an argument to the launch file: `use_gpu_ray`. In this way we don't need to switch branch everytime and we can use the same version in the docker.
This has been added in commit 4401d34 (remember to pull also the **modular** package ADVRHumanoids/modular_hhcm@24168fcb951e6660ce8adb8a0682b88d7df78ed9)

To use the `gpu_ray` plugin instead of `ray` run:
`mon launch concert_gazebo concert.launch velodyne:=true rviz:=true use_gpu_ray:=true`

P.S.
There are currently some weird errors in the Travis CI build (seems packages.ros.org is unreachable, although it's not if you build locally), so if you use the docker just rebuild it manually with `build_docker.sh`

**Comment by Morgantiz** [comment]
With the use_gpu_ray:=true option the problem disappears, Thanks!
