### ISSUE TITLE
Robot-Model mismatch in number of joints

### ISSUE THREAD

**Issue by manuelvogel12** [ADVRHumanoids/concert_description#9]
I am a student of Jakob Thumm and i have the problem regarding running the Xbot ROS API example notebook on the concert_description robot. So whenever I try 
``` q0 = robot.getJointPosition() ``` , I get a 13 dimensional vector back. But the model.setJointPosition(q0) assumes a 19 dimensional vector. I guess this is because of ```cfg.set_string_parameter('model_type', 'RBDL')```
Which model_type do I have to choose for the concert robot?
Another issue I encounter is that ros_control stops whenever i send a ```robot.move()``` over the xbot.RobotInterface. Is this expected behaviour?

**Comment by EdoardoRomiti** [comment]
Hi @manuelvogel12 , you are using this example: [ADVRHumanoids/xbot2_examples/tree/master/src/ros_api_tutorial.ipynb](https://github.com/ADVRHumanoids/xbot2_examples/blob/master/src/ros_api/ros_api_tutorial.ipynb), correct?
That example is originally thought for a _fixed base_ robot, while the CONCERT platform is _floating base_. You should therefore set the **is_fb** flag in the notebook to True, since otherwise it defaults to False:
`cfg = get_xbot_cfg(is_fb=False)`
This will make the RBDL library know you are working with a floating base robot and so will enlarge the robot state vector with the 6 coordinates of the base. 

This should solve your first issue. Does the second issue still happen after correcting this? Can you provide some logs in that case?

**Comment by manuelvogel12** [comment]
Actually both issues happend after I set ```is_fb``` to True. 
The outputs of 
```
model.setJointPosition(q)
model.setJointVelocity(v)
model.setJointAcceleration(a)
model.update()
tau = model.computeInverseDynamics()

robot.setPositionReference(q) 
robot.setVelocityReference(v)
robot.setEffortReference(tau)
```
are: 
```
ERROR in setJointPosition : q has wrong size 13 != robot joint number 19
ERROR in setJointVelocity : qdot has wrong size 13 != robot joint number 19
ERROR in setJointAcceleration : qddot has wrong size 13 != robot joint number 19
ERROR in setEffortReference : tau has wrong size 19 != robot joint number 13
```
So the 3 lines with model.* return the first 3 lines, and ```robot.setEffortReference(tau)``` throws the last line.

Regarding the second issue:
Whenever a robot.move is send, I get the error 
```
/xbot2: [err ][J_wheel_A] [J_wheel_A] resource 'Impedance' undefined
/xbot2: [err ][ros_ctrl] unable to acquire ctrl mode 'Impedance' for joint 'J_wheel_A', stopping (maybe another plugin is 
            using this joint?)

```

**Comment by alaurenzi** [comment]
About this second issue, here's the workaround: 
```python
ctrl = {f'J_wheel_{l}': xbot.ControlMode.Velocity() for l in ('A', 'B', 'C', 'D')}
robot.setControlMode(ctrl)
```

Explanation: wheels don't support setting an impedance, yet by default the `RobotInterface` tries to send the full command message.

This error only appears in our latest development branch (I use this on Docker in order to have beta testers for free :-D ).
I realize it's not super user-friendly, but I am working on improving the situation so that.

**Comment by manuelvogel12** [comment]
Ok thank you, I will try it

**Comment by EdoardoRomiti** [comment]
Regarding the first issue, basically the problem is that RBDL consider in the state vector also the virtual joint coordinates of the floating base (therefore 19 element) while xbot only the actuated joints (13 elements).
So what you could do is extend the state vector when you are setting the state of the __model__, for instance:
```
q_ext = np.insert(q, 0, np.zeros(6))
v_ext = np.insert(v, 0, np.zeros(6))
a_ext = np.insert(a, 0, np.zeros(6))

# compute inverse dynamics torque
model.setJointPosition(q_ext)
model.setJointVelocity(v_ext)
model.setJointAcceleration(a_ext)
model.update()
tau = model.computeInverseDynamics()
```
(instead of zeros you can use the first 6 values to set the pose of the floating base, although the model.setFloatingBase() method which accepts the pose as an Eigen::Affine3d can be handier for that purpose).

While instead when setting the computed effort to the __robot__ remove the first 6 virtual joint efforts:
```
# set reference to robot
robot.setPositionReference(q)
robot.setVelocityReference(v)
robot.setEffortReference(tau[6:])
```

**Comment by manuelvogel12** [comment]
This worked, thank you very much for your time
